
export const Actions = {
    LOGIN: "SET_USER_STATE",
    SET_TOKEN: "SET_AUTH_TOKEN",
    LOGOUT: "SET_USER_LOGOUT",
    NOTIFY: "SHOW_SNACKBAR",
    NOTIFY_CLOSE: "CLOSE_SHOW_SNACKBAR",
    NOTIFY_LOGOUT: "USER_LOGOUT_ACTION"
}