const Actions = {
  LOGIN: 'SET_USER_STATE',
  SET_TOKEN: 'SET_AUTH_TOKEN',
  LOGOUT: 'SET_USER_LOGOUT',
  MARK_INTRO_COMPLETE: "SET_INTRO_SCREEN_AS_SEEN",
  MARK_INTRO_INCOMPLETE: "SET_INTRO_SCREEN_AS_FRESH",
  SET_ACTIVE_TAB_INDEX: "SET_DEFAULT_ACTIVE_TAB_HOME",
  SET_USER_FUE: "SET_USER_INTERACTION_TYPE"
};

export default Actions;
